Fiorello-backend/EntityFrameworkProject/Models/SliderDetail.cs
namespace EntityFrameworkProject.Models
{
    public class SliderDetail : BaseEntity
    {
        public string Header { get; set; }
        public string Description { get; set; }
        public string SignImage { get; set; }
    }
}

Fiorello-backend/EntityFrameworkProject/Areas/AdminArea/Controllers/SliderDetailController.cs
using EntityFrameworkProject.Data;
using EntityFrameworkProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class SliderDetailController : Controller
    {
        private readonly AppDbContext _context;

        public SliderDetailController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<SliderDetail> sliderDetails = await _context.SliderDetails.Where(m => !m.IsDeleted).AsNoTracking().OrderByDescending(m => m.Id).ToListAsync();
            return View(sliderDetails);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SliderDetail sliderDetail)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }


                //bool isExist = await _context.SliderDetails.AnyAsync(m => m.t.Trim() == sliderDetail.Name.Trim());

                //if (isExist)
                //{
                //    ModelState.AddModelError("Name", "Category already exist");
                //    return View();
                //}

                //change exist data is delete

                //var data = await _context.Categories.Where(m => m.IsDeleted == true).FirstOrDefaultAsync(m=>m.Name.Trim() == category.Name.Trim());

                //if(data is null)
                //{
                //    await _context.Categories.AddAsync(category);
                //}
                //else
                //{
                //    data.IsDeleted = false;
                //}

                await _context.SliderDetails.AddAsync(sliderDetail);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }

        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            SliderDetail sliderDetail = await _context.SliderDetails.FindAsync(id);

            if (sliderDetail == null) return NotFound();

            return View(sliderDetail);
        }

        //delete from database

        //[HttpPost]
        //public async Task<IActionResult> Delete(int id)
        //{
        //    Category category = await _context.Categories.FirstOrDefaultAsync(m => m.Id == id);

        //    _context.Categories.Remove(category);

        //    await _context.SaveChangesAsync();

        //    return RedirectToAction(nameof(Index));
        //}


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            SliderDetail sliderDetail = await _context.SliderDetails.FirstOrDefaultAsync(m => m.Id == id);

            sliderDetail.IsDeleted = true;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                SliderDetail sliderDetail = await _context.SliderDetails.FirstOrDefaultAsync(m => m.Id == id);

                if (sliderDetail is null) return NotFound();

                return View(sliderDetail);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SliderDetail sliderDetail)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(sliderDetail);
                }

                SliderDetail dbSliderDetail = await _context.SliderDetails.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbSliderDetail is null) return NotFound();

                

                // dbCategory.Name = category.Name;

                _context.SliderDetails.Update(sliderDetail);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

Fiorello-backend/EntityFrameworkProject/Areas/AdminArea/Views/SliderDetail/Create.cshtml
@model SliderDetail
@{
    ViewData["Title"] = "Create";
}


<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <span class="text-danger">@ViewBag.Message</span>
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-description">
                            SliderDetail
                        </p>
                        <form asp-controller="SliderDetail" asp-action="Create" class="forms-sample" method="post">
                            <div class="form-group">
                                <label for="name">Header</label>
                                @*<input maxlength="" minlength="" type="text" class="form-control" asp-for="Name">*@
                                <textarea class="form-control" asp-for="Header" id="slider-header" rows="8"></textarea>

                                <span class="text-danger my-1" asp-validation-for="Header"></span>

                            </div>
                            <label for="name">Description</label>
                            <input maxlength="100" type="text" class="form-control" asp-for="Description">
                            <label for="name">SignImage</label>
                            <input maxlength="100" type="text" class="form-control" asp-for="SignImage">
                            <button type="submit" class="btn btn-primary mr-2 my-3">Submit</button>
                            <a asp-controller="SliderDetail" asp-action="Index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <partial name="_ValidationPartial" />
    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("slider-header");
    </script>


}

Fiorello-backend/EntityFrameworkProject/Areas/AdminArea/Views/SliderDetail/Detail.cshtml
@model Category
@{
    ViewData["Title"] = "Detail";
}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            Category detail
        </div>
        <div class="card-body">
            <p class="card-text">@Model.Name</p>
        </div>
    </div>
</div>

Fiorello-backend/EntityFrameworkProject/Areas/AdminArea/Views/SliderDetail/Edit.cshtml
@model Category

@{
    ViewData["Title"] = "Edit";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <span class="text-danger">@ViewBag.Message</span>
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-description">
                            Category
                        </p>
                        <form asp-controller="Category" asp-action="Edit" class="forms-sample" method="post">
                            <div class="form-group">
                                <label for="exampleInputUsername1">Name</label>
                                <input maxlength="" minlength="" type="text" class="form-control" asp-for="Name">
                                <span class="text-danger my-1" asp-validation-for="Name"></span>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <a asp-controller="Category" asp-action="Index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{

    <partial name="_ValidationPartial" />
}

Fiorello-backend/EntityFrameworkProject/Areas/AdminArea/Views/SliderDetail/Index.cshtml
@model IEnumerable<SliderDetail>

@{
    ViewData["Title"] = "SliderDetail";
}


<div class="container-fluid my-3 mx-3">
    <div class="table-responsive pt-3">
        <div class="create-btn mb-3">
            <a asp-controller="SliderDetail" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Header
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Sign
                    </th>
                    <th style="text-align: center;">
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (SliderDetail sliderDetail in Model)
                {
                    <tr>
                        <td>
                            @Html.Raw(sliderDetail.Header)
                        </td>
                        <td>
                            @Html.Raw(sliderDetail.Description)
                        </td>
                        <td>
                            @Html.Raw(sliderDetail.SignImage)
                        </td>
                        <td style="text-align: center;">
                            <a asp-action="Detail" asp-route-id="@sliderDetail.Id" class="btn btn-info"><i class="mdi mdi-information mx-0"></i></a>
                            <a asp-action="Edit" asp-route-id="@sliderDetail.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></a>
                            <form style="display: inline-block;" asp-action="Delete" asp-route-id="@sliderDetail.Id" method="post">
                                <button type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i></button>
                            </form>
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    </div>
</div>